---
title: "Midterm"
author: "Sean Kim"
format:
  html:
    embed-resources: true
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(data.table)
library(readxl)
```

```{r}

```

```{r}
if (!file.exists("ca-hcai-preventablehospitalizations-county")) 
  download.file( 
    url = "https://data.chhs.ca.gov/dataset/f2b33545-db0a-4a53-a611-41de532e7c53/resource/7c7aed93-3643-43b8-92fc-324bf8fc13f2/download/ca-hcai-preventablehospitalizations-county.csv", 
    destfile = "ca-hcai-preventablehospitalizations-county", 
    method = "libcurl", 
    timeout = 1000 )


PrevHosp <- fread("ca-hcai-preventablehospitalizations-county") 
```

```         
```

```{r}
if (!file.exists("pcsa")) 
  download.file( 
    url = "https://data.chhs.ca.gov/dataset/061494a3-e8c7-4615-a22f-b2851d44eb09/resource/0ba7c904-2302-400a-ba27-b8e8e5c1ab4a/download/pcsa.csv", 
    destfile = "pcsa", 
    method = "libcurl", 
    timeout = 1000 )


PrimCareShort <- fread("pcsa") 
```

```{r}
if (!file.exists("hciretailfoodenvironment75cacoreplct201715nov17")) 
  download.file( 
    url = "https://data.chhs.ca.gov/dataset/714a9d67-3291-447b-94b9-9d3e1063d176/resource/c58c1b68-6545-4039-bc52-6facf120a4c7/download/hciretailfoodenvironment75cacoreplct201715nov17.xlsx", 
    destfile = "hciretailfoodenvironment75cacoreplct201715nov17", 
    method = "libcurl", 
    timeout = 1000 )


HealthyFood <- read_xlsx("hciretailfoodenvironment75cacoreplct201715nov17") 
```

```{r}
if (!file.exists("retail-availability-of-electronic-smoking-devices-by-county")) 
  download.file( 
    url = "https://data.chhs.ca.gov/dataset/8eb8839f-52a1-410b-8c4a-5b1c1678bbc2/resource/21fec3a1-ae82-49f4-ae97-fd8c78ca22ee/download/retail-availability-of-electronic-smoking-devices-by-county.csv", 
    destfile = "retail-availability-of-electronic-smoking-devices-by-county", 
    method = "libcurl", 
    timeout = 1000 )


Ecig <- fread("retail-availability-of-electronic-smoking-devices-by-county") 
```

```{r}
food <- HealthyFood %>% 
  select(!ind_id:ind_definition) %>% 
  select(!geotypevalue:geoname) %>% 
  select(!race_eth_code:race_eth_name) %>% 
  select(!county_fips:strata_two_name) %>% 
  select(!ca_decile:version) %>% 
  rename(county = county_name) 
```

```{r}
hosp <- PrevHosp %>% 
  select(!Count_ICD9:RiskAdjRate_ICD9) %>% 
  select(!AnnotationCode:AnnotationDesc) %>% 
  filter(Year == 2017) %>% 
  filter(County != "STATEWIDE") %>% 
  mutate(Count_ICD10 = as.numeric(gsub(",", "", Count_ICD10))) %>% 
  mutate(Population_ICD10 = as.numeric(gsub(",", "", Population_ICD10))) %>% 
  rename(county = County)
  

```

```{r}
hosp20 <- PrevHosp %>% 
  select(!Count_ICD9:RiskAdjRate_ICD9) %>% 
  select(!AnnotationCode:AnnotationDesc) %>% 
  filter(Year == 2020) %>% 
  filter(County != "STATEWIDE") %>% 
  filter(!PQIDescription %in% c("Overall Composite", "Acute Composite", "Chronic Composite", "Diabetes Composite")) %>% 
  mutate(Count_ICD10 = as.numeric(gsub(",", "", Count_ICD10))) %>% 
  mutate(Population_ICD10 = as.numeric(gsub(",", "", Population_ICD10))) %>% 
  rename(county = County)
```

```{r}
hospcomposite <- PrevHosp %>% 
  select(!Count_ICD9:RiskAdjRate_ICD9) %>% 
  select(!AnnotationCode:AnnotationDesc) %>% 
  filter(Year == 2020) %>% 
  filter(County != "STATEWIDE") %>% 
  filter(PQIDescription %in% c("Overall Composite", "Acute Composite", "Chronic Composite", "Diabetes Composite")) %>% 
  mutate(Count_ICD10 = as.numeric(gsub(",", "", Count_ICD10))) %>% 
  mutate(Population_ICD10 = as.numeric(gsub(",", "", Population_ICD10))) %>% 
  rename(county = County)
```

```{r}
hospDMshort <- hosp %>% 
  filter(PQIDescription == "Diabetes Short-term Complications")

hospDMlong <- hosp %>% 
  filter(PQIDescription == "Diabetes Long-term Complications")

hospDMuncont <- hosp %>% 
  filter(PQIDescription == "Uncontrolled Diabetes")

hospDMamp <- hosp %>% 
  filter(PQIDescription == "Lower-Extremity Amputation (Diabetes)")

hospHeart <- hosp %>% 
  filter(PQIDescription == "Heart Failure")

hospHTN <- hosp %>% 
  filter(PQIDescription == "Hypertension")
```

```{r}
pcp <- PrimCareShort %>% 
  select(!MSSA_ID:MSSA_NAME) %>% 
  select(!EST_Physicians:EST_FNPPA) %>% 
  select(!PCSA) %>% 
  filter(!is.na(MSSA_COUNTY)) %>% 
  rename(county = MSSA_COUNTY)
```

```{r}
pcp <- pcp %>% 
  group_by(county) %>% 
  summarize(Population = mean(Total_Population, na.rm = TRUE), 
            Providers = mean(EST_Providers, na.rm = TRUE), 
            Average_ProviderRatio = mean(Provider_Ratio, na.rm = TRUE), 
            Average_Score_Provider = mean(Score_Provider_Ratio, na.rm = TRUE), 
            Average_Pct_100FPL = mean(PCT_100FPL, na.rm = TRUE), 
            Average_Score_Poverty = mean(Score_Poverty, na.rm = TRUE), 
            Average_Score_Total = mean(Score_Total, na.rm = TRUE), 
            )
```

```{r}
hosp20 <- hosp20 %>% 
  full_join(pcp, by = "county")

hospcomposite <- hospcomposite %>% 
  full_join(pcp, by = "county")

str(hosp20)
summary(hosp20$RiskAdjRate_ICD10)
summary(hosp20$Average_ProviderRatio) 
summary(hosp20$Average_Pct_100FPL)

hosp20$Average_ProviderRatio[is.na(hosp20$Average_ProviderRatio)] <- 0



```

```{r}
ggplot(pcp, aes(x = 1, y = Average_ProviderRatio, group = 1)) +
  geom_boxplot() +
  labs(title = "Distribution of Population:Provider Ratios in 2020 in California Counties",
       x = NULL,  # No x-axis label
       y = "Provider Ratio") +
  theme_minimal() +
  theme(axis.text.x = element_blank(),  # Remove x-axis labels
        axis.ticks.x = element_blank())  # Remove x-axis ticks
```

Need to have average for CA

```{r}
QuartilesCAProvider <- quantile(pcp$Average_ProviderRatio, probs = seq(0, 1, 0.25), na.rm = TRUE)
kable(data.frame(Quartile = c("Min", "Q1", "Median", "Q3", "Max"),
                 Value = QuartilesCAProvider),
      format = "html",
      caption = "Quartiles of Average Provider Ratio in California")
```

```{r}
ggplot(pcp, aes(x = Average_Score_Provider)) +
  geom_histogram(binwidth = 0.1, fill = "skyblue", color = "black", alpha = 0.7) +
  labs(title = "Distribution of Provider Scores by County",
       x = "Provider Score",
       y = "Frequency") +
  theme_minimal()
```

```{r}
score_cutoffs <- PrimCareShort %>%
  select(Score_Provider_Ratio, Provider_Ratio) %>%
  distinct() %>%
  arrange(Score_Provider_Ratio, Provider_Ratio)
print(score_cutoffs)
```

0 is 0-1000; 1 is 1000-1500; 2 is 1500-2000; 3 is 2000-2500; 4 is 2500-3000; 5 is \>3000

```{r}
ggplot(hosp20, aes(x = 1, y = RiskAdjRate_ICD10)) +
  geom_boxplot() +
  labs(title = "Distribution of Risk Adjusted Rates by PQI Code",
       x = "PQI Code",
       y = "Risk Adjusted Rate") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +  
  facet_wrap(~PQIDescription, scales = "free_y", ncol = 3)+
  theme(plot.title = element_text(size = 8),  
        axis.title = element_text(size = 8),  
        axis.text = element_text(size = 7),   
        strip.text = element_text(size = 8), 
        strip.background = element_blank())  
```

```{r}
ggplot(hosp20, aes(x = Average_ProviderRatio, y = RiskAdjRate_ICD10)) +
  geom_point(size = 0.5) +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  facet_wrap(~PQIDescription, scales = "free_y", ncol = 5)+
  labs(title = "Scatter Plot of Risk-Adjusted Rate vs Average Provider Ratio",
       x = "Average Provider Ratio",
       y = "Risk-Adjusted Rate") +
  theme(plot.title = element_text(size = 6), 
        axis.title = element_text(size = 6), 
        axis.text = element_text(size = 6),  
        strip.text = element_text(size = 6),  
        strip.background = element_blank())    
```

```{r}

ggplot(hospcomposite, aes(x = Average_Score_Provider, y = RiskAdjRate_ICD10)) +
  geom_point(size = 0.5) +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  facet_wrap(~PQIDescription, scales = "free_y", ncol = 2)+
  labs(title = "Scatter Plot of Risk-Adjusted Rate vs Average Provider Ratio",
       x = "Average Provider Ratio",
       y = "Risk-Adjusted Rate") +
  theme(plot.title = element_text(size = 6),  
        axis.title = element_text(size = 6),
        axis.text = element_text(size = 6),   
        strip.text = element_text(size = 6), 
        strip.background = element_blank())
```

Summary Statistics:

```{r, results-'asis'}
library(knitr)

hospoverall <- hospcomposite %>% 
  filter(PQIDescription == "Overall Composite")

result_table <- hospoverall %>%
  group_by(county) %>%
  summarize(
    Average_RiskAdjRate = mean(RiskAdjRate_ICD10, na.rm = TRUE),
    Average_Provider_Score = mean(Average_Score_Provider, na.rm = TRUE)
  ) %>%
  arrange(desc(Average_RiskAdjRate)) %>%
  slice_head(n = 10)

kable(result_table, format = "html", caption = "Counties Ordered by Highest Composite Risk-Adjusted Rates",
      col.names = c("County", "Risk-Adjusted Rate", "Provider Score"))

result_table_score <- hospoverall %>%
  group_by(county) %>%
  summarize(
    Average_RiskAdjRate = mean(RiskAdjRate_ICD10, na.rm = TRUE),
    Average_Provider_Score = mean(Average_Score_Provider, na.rm = TRUE)
  ) %>%
  arrange(desc(Average_Provider_Score)) %>%
  slice_head(n = 10)

kable(result_table_score, format = "html", caption = "Top 10 Counties by Provider Score",
      col.names = c("County", "Risk-Adjusted Rate", "Provider Score"))
```
